export default {
  ///
  emailIsRequired: 'Email is required',
  invalidEmail: 'Invalid email',
  passwordIsRequired: 'Password is required',
  invalidPassword: 'Invalid password',
  confirmPasswordIsRequired: 'Confirm password is required',
  invalidConfirmPassword: 'Invalid confirm password',
  passwordsDontMatch: 'Passwords do not match',
  contactIsRequired: 'Contact is required',
  invalidcontact: 'Invalid contact',
  nameIsRequired: 'Name is required',

  ///

  registerSuccessfully: 'Registered successfully',
  /////
  splashscreen: 'Splash',
  skip: 'Skip',
professional: 'The professional specialist is near',
profdesc: 'Now it is very easy to find your home service, we have many highly experienced specialists',
onboardingscreen: 'OnBoarding',
welcomescreen: 'Welcome',
onlywomen: 'This app is for women only',
register: 'Register as',
bussiness: 'Business',
user: 'User',
alreadyhaveacc: 'Already have an account?',
sign_In: 'Sign In',
buttonopacity: 0.7,
service_detial: 'Service Details',
loginscreen: 'Login',
signupscreen: 'Signup',
signupUser: 'Signup User',
signupArtist: 'Signup Artist',
total_Duration: 'Total Duration',
total_Cost: 'Total Cost',
signin: 'Sign In',
travel_Cost: 'Travel Cost',
welcomeback: 'Hello! Welcome back, we missed you',
email: 'Email',
password: 'Password',
forgotpassword: 'Forgot password?',
orsignin: 'Or sign in with',
orsignup: 'Or sign up with',
donthaveacc: 'Don’t have an account? Signup',
createacc: 'Create Account',
fillinfo: 'Fill in your information below or sign up with \n your social account.',
name: 'Name',
jhon: 'John Doe',
phonenum: 'Phone Number',
num: '603.555.0123',
expemail: 'example@gmail.com',
pass: '********',
address: 'Address',
businessemail: 'Business Email',
businessname: 'Business Name',
Businessbrand: 'Business Brand',
services: 'Services',
businesspayment: 'Business Payment Account',
ibannum: 'IBAN (International Bank Account Number)',
agreewithterms: 'I agree with the terms and conditions',
signup: 'Sign Up',
category: 'Category',
selectCategory: 'Select Category',
locationscreen: 'Location',
whatloction: 'What is your location?',
needlocation: 'We need to know your location to suggest nearby services.',
selectcity: 'Select City',
allcities: 'All Cities',
allowloc: 'Allow access to location',
addLocation: 'Add Location',
enterlocman: 'Enter location manually',
getartist: 'Get the best artist\n at your doorstep',
manuallocationscreen: 'Manual Location',
enteryourlocation: 'Enter your location',
goldenavnue: 'Golden Avenue',
usecurrenloc: 'Use my current location',
searchresult: 'Search Result',

prestonroad: '8502 Preston Road, English..',
uploaddocsscreen: 'Upload Documents',
uploaddocs: 'Upload documents and images',
uploadworklicense: 'Upload your work license',
uploadyourdocs: 'Upload your document here',
uploadIdcard: 'Upload your ID card',
uploadwork: 'Upload images of your work',
dumytext: 'Lorem ipsum dolor sit amet, consectetur.',
uploadphotos: 'Upload photos',
compsignup: 'Complete Registration',
homescreen: 'Home',
bottomTab: 'Bottom Tab',
managePaymentScreen: 'Manage Payment',
location: 'Location',
newyork: 'New York, USA',
profileapprove: 'Your profile has been approved',
setavailability: 'Set Availability',
online: 'Online',
activebooking: 'Active Bookings',
totalbooking: 'Total Bookings',
totalview: 'Total Views',
totalfavorite: 'Total Favorites',
myearning: 'My Earnings',
thismonth: 'This Month',
sr: 'Saudi Riyal',
myservices: 'My Services',
seeall: 'See All',
seeLess: 'See Less',
earning: 'Earnings',
wallet: 'Wallet',
$: 'Dollar',
managePayout: 'Manage Payouts',
paymentHistory: 'Payment History',
pendigEarnings: 'Pending Earnings',
widthraw: 'Withdrawals',
transactionTitle: 'Transaction Title',
price: '0.00 SAR',
description: 'Description',
saudiaPrice: '0.00 Saudi Riyal',
myServices: 'My Services',
noServicesAddedd: 'No services added',
loriumText: 'Lorem ipsum dolor sit amet, consectetur. Sit in turpis not ante at an inappropriate time.',
addService: 'Add Services',
haircut: 'Haircuts',
makeup: 'Makeup',
shaving: 'Shaving',
hairdry: 'Hair Drying',

massage: 'Massage',
henna: 'Henna',
nailcare: 'Nail Care',
feetcare: 'Feet Care',
skincare: 'Skin Care',
next: 'Next',
artist: 'Artist',
jenny: 'Jenny Wilson',
profile: 'Profile',
yourprofile: 'Your Profile',
offdays: 'Days Off',
membership: 'Membership',
paymentmethod: 'Payment Methods',
travelcost: 'Travel Costs',

settings: 'Settings',
transaction: 'Transactions',
helpcenter: 'Help Center',
privacypolicy: 'Privacy Policy',
logout: 'Log Out',
profilescreen: 'Profile',
travelCostscreen: 'Travel Cost',
artistdetailscreen: 'Artist Details',
artistDetailsUser: 'Artist Details User',
addServices: 'AddServices',
Services: 'Services',
MyService: 'My Service',
add_Service_Photos: 'Add Service Photos',
lorem_ipsum: 'Lorem ipsum dolor sit amet, consectetur.',
service_Description: 'Service Description',
add_Service_Description: 'Add Service Description',
add_Title_and_Rates: 'Add Title and Rates',
title: 'Title',
faux_hawk: 'Faux Hawk',
rates: 'Rates',
SR_24: '24.00 Saudi Riyal',
add_More_Types: 'Add More Types +',
payment_Mode: 'Payment Mode',
credit_Card: 'Credit Card',
Cash: 'Cash',
duration_Time: 'Duration Time',
hair_Cut: 'Hair Cut',
hair_Coloring: 'Hair Coloring',
hair_Wash: 'Hair Wash',
type20: '20 Types',
type12: '12 Types',
edit: 'Edit',
jobdone: 'Job Done: ',
jobcancel: 'Job Cancelled: ',
zero_One: '01',
min15: '15 Minutes',
km15: '1.5 km',
pm11: '11 PM',
am11: '11 AM',
monsun: 'Mon Sun',

travelingcost: 'Travel Cost 20 Saudi Riyal',
travelingCost: 'Travel Cost',
favorite: 'Favorites (50)',
review: 'Reviews',
gallery: 'Gallery',
review1: 'Review',
aboutus: 'About Us',
selectHairCut: 'Select Haircut',
dollar24: '24.00 Dollars',
dollar: 'Dollar',
mohawk: 'Mohawk',
buzz_cut: 'Buzz Cut',
pompadour: 'Pompadour',
side_part: 'Side Part',
crew_cut: 'Crew Cut',
add_Type: 'Add Type',
booking: 'Bookings',
booking_Detail: 'Booking Details',
remind_Me: 'Remind Me',
aug_25: 'August 25, 2024 - 10:00 AM',
g85: 'G8502 Preston Road, Englewood',
service_id: 'Service ID: ',
view_Detail: 'View Details',
cancle: 'Cancel',
comming_Tab: 'Upcoming',
cancled: 'Cancelled',
view_Electric_Recipt: 'View Electronic Receipt',
rebook: 'Rebook',
aug_28: 'August 28, 2024 - 10:00 AM',
upcoming: 'Upcoming',
completed: 'Completed',
onGoing: 'Ongoing',
you_have: 'You have arrived at the barbershop/salon',
ok: 'Yes',
arrived: 'Arrived Location',
new_Booking_Request: 'New Booking Request',
july_Time: 'August 25, 2024 - 10:00 AM',
type08: '08 Types',
type04: '04 Types',
type05: '05 Types',
types: 'Types',
alservice: 'Services (18)',
allservice: 'All Services',
addservices: ' + Add Services',
face_makeup: 'Face Makeup',
zerotime: '00:00 - 00:00',
getDirection: 'Direction',
cancel_Request: 'Cancel Request',
bookingAccepted: 'BookingAccepted',
contactUs: 'Contact Us',
callNumber: '(406) 555-0120',

exampleEmail: 'example@gmail.com',
viewOnMap: 'View on Map',
prestonRd: '8502 Preston Road, Englewood, MN 98380',
bookingDetail: 'Booking Accepted',
threeKm: '3.5 km/50 minutes',
serviceRequired: 'Required Services',
dollar_24: '24.00 Riyal',
saudiRiyal: 'Riyal',
decline: 'Decline',
request_reservation: 'Request New Reservation',
rs: 'SR',
booking_Completed: 'Booking Completed',
you_Have_Been: 'You have been successfully completed!',
How_was: 'How was your experience with Jenny?',
your_Overall: 'Your Overall Rating',
add_Detail_Review: 'Add Detailed Review',
enter_Here: 'Enter Here',
addPhoto: 'Add Photo',
submit: 'Submit',
cancellation_Boking: 'Cancel Booking',
please_specify: 'Please specify the reason for cancellation:',
change_the: 'Change the Schedule',
weather_conditions: 'Weather Conditions',
availability_of_parking: 'Availability of Parking',
lack_amenities: 'Lack of Amenities',
alternative_Option: 'I have an alternative option',
last: 'Last',
enter_Your_Reason: 'Enter Your Reason',
workinghours: 'Add Working Hours',
addhours: 'Add Hours',
photos: 'Photos (8)',
photosLength: 'Photos',
addphotos: 'Add Photo',
weather_Conditions: 'Weather Conditions',
availability_Parking: 'Availability of Parking',
lack_Of_Amenities: 'Lack of Amenities',
i_have_Alternative_Option: 'I have an alternative option',
basic_Membership_Plan: 'Basic Membership Plan',
free: 'Free',
includes: 'Includes',
offline_booking: 'Offline Booking',
chat_with_custumer: 'Chat with Customers Before Booking',
future_booking: 'Future Booking and Stop Dates Specified by the Artist',
active: 'Active',
travel_Cost_PerKilo: 'Travel Cost Per Kilometer',
sr4: 'SR4.00',
save: 'Save',
mon: 'Monday',
octfive: '5 Oct',
addMoreOff: 'Add More Off',
pay_Cash: 'Pay Cash',
credit_Debit: 'Credit and Debit Card',
add_New_Card: 'Add New Card',
notification_setting: 'Notification Settings',
password_manager: 'Password Manager',
delete_account: 'Delete Account',
your_Transaction: 'Your Transactions',
today: 'Today',
april_date: 'April 24 | 7:30 AM',
twenty_Dollar: '- 20.00 Dollars',
yesterday: 'Yesterday',
thirty_Dollar: '- 30.00 Dollars',

twenty_july: '22 July 2023',
hair_Color: 'Hair Color',
twenty_One_July: '21 July 2023',
current_Password: 'Current Password',
new_Password: 'New Password',
confirm_Password: 'Confirm New Password',
change_Password: 'Change Password',
seek: 'Search',
instructions: 'Instructions',
callUs: 'Call Us',
everyone: 'Everyone',
general: 'General',
account: 'Account',
signature_Saloon: 'What is the Signature Salon?',
lorium_ispum_text:
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
how_To_Cancle: 'How to Cancel an Appointment?',
how_To_See_Preseverd: 'How to View Saved Salons?',
check_Previosly_Booking: 'How to Check a Previously Booked Appointment?',
verify_Transaction: 'How to Verify a Transaction?',
check_nearby_Saloon: 'How to Add a Check for Nearby Salons?',
add_Review: 'How to Add a Review?',
customer_Service: 'Customer Service',
whatsapp: 'WhatsApp',
website: 'Website',
facebook: 'Facebook',
twitter: 'Twitter',
instagram: 'Instagram',
four_Number: '(480) 555-0103',
addresses: 'Addresses',
address_Dummy: '84 W La Entrada, Corrales, New York, United States',
newYork_address: 'New York, United States',
uploadworkphotos: 'Upload Your Work Photos',
uploadphotoshere: 'Upload Your Photos Here',
photocategory: 'Photo Category',
hairname: 'Hair Name',
addtype: 'Add Type',
reviews: 'Reviews',
searchreviews: 'Search in Reviews',
filter: 'Filter',
verified: 'Verified',
latest: 'Latest',
withphotos: 'With Photos',

detailedreview: 'Detailed Reviews',
opennow: 'Open Now',
dalethiel: 'Dale Thiel',
followers45: '45 Followers',
monthsago11: '11 months ago',
tiffny: 'Tiffany Nietzsche',
dateOfBirth: 'Date of Birth',
dayMonthYear: 'Day/Month/Year',
gender: 'Gender',
heChooses: 'He Chooses',
updateProfile: 'Update Profile',
are_You_Sure: 'Are you sure you want to log out?',
yes_Logout: 'Yes, Log Out',
privacy_Policy: 'Privacy Policy',
canclation_Policy: 'Cancellation Policy',
terms_and_Condition: 'Terms and Conditions',
dummy_Text_Policy:
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. We only allow the minimum activity we practice through work, and we do not leave it away from anything that may result from that.',
dummy_Text_Lorium:
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
lorium_Text_Small:
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
edit_About: 'Edit About',
modify_Working_Hour: 'Modify Working Hours',
social_Media: 'Social Media',
social_Media_Editing: 'Edit Social Media',
artistUser: '@artistuser',
editing_Contact_Detail: 'Edit Contact Details',
hairCut_HairStyling: 'Hair Cutting and Styling',
special_Offer: 'Special Offers Package, valid until December 10, 2024',
onetwofiveDollar: '125.00 USD',
bookNow: 'Book Now',
continuemobile: 'Continue with Mobile',
SignupUser: 'SignupUser',
userHome: 'UserHome',
servicesDesc: 'Get the best\n artist\n at your doorstep',
searchsaloon: 'Salon search, specialized...',
toprated: 'Top Rated Artists',
nearartist: 'Near the Artist',
onlinestore: 'Active Stores',
onlinestorescreen: 'OnlineStores',
onlinestoresdetailcreen: 'OnlineStoreDetail',
brand_Name: 'Brand Name',
visiting_Site: 'Visit Site',
notice: 'Notice',
userArtist: 'UserArtistScreen',
addworkinghour: 'Add Working Hours',
adddesc: 'Add Description',
enterdesc: 'Enter Description',
contactndadress: 'Add Address and Contact',
change: 'Change',
premiummember: 'Premium Membership Plan',
riyal50: '50.00 SAR',
subcribenow: 'Subscribe Now',
off: 'About',
notification_screen: 'Notifications',
notification: 'Notifications',
user_Bottom_Stack: 'UserBottomStack',
travelCost_20: 'Travel Cost 20 SAR',
moonSoon: 'Moon Sun | 11 AM - 11 PM',
comments: '(107 Comments)',

cancelation: 'Cancellations',
jobDone: 'Job Done',
startingFrom: 'Starting from 24.00 SAR',
timeduration: 'Total Duration 1 Hour',
bookapointment: 'Booking',
riyal28: '28.00 SAR',
cancelbooking:
  'The artist may cancel your booking due to \n the service hour is about to end.',
oneselect: 'One service selected',
workinghour: 'Working Hours',
bookapointment_screen: 'BookAppointment',
bookAppointment_screen: 'BookAppointment',
bookingDetails_screen: 'BookingDetails',
bookapoint: 'Book Appointment',
forcancelation:
  'To cancel, the client must be charged a deposit ranging from 20-50% of the total cost.',
hour: '1 Hour',
youraddress: 'Your Address',
changeaddress: 'Change Address',
day: 'Day',
time: 'Time',
saved: 'Saved',
useryourprofile_screen: 'UserYourProfile',
saved_screen: 'Saved',
onehour: 'Duration 1 Hour',
userNotificationsScreen: 'UserNotifications',
congrate_Your_Reservation: 'Congratulations, your booking for a relaxing spa session has been confirmed.',
your_Favorite_hairStyle:
  'Your favorite hair stylist, Lisa, is available for appointments on Wednesday.',
estimated_Weight_Time: 'The estimated waiting time at the salon is about 25 minutes.',
augs17: 'August 17, 2023',
augs18: 'August 18, 2023',
fifty_Percent_Discount: '50% discount on hair dyes!',

};